create table sensor
(
    id               integer generated by default as identity
        primary key,
    name             varchar(30) not null
        constraint name
            unique,
    last_measurement timestamp
);

alter table sensor
    owner to postgres;

